name: publish package to serverless-hub

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install requests
      - name: NPM install
        run: |
          npm install --production
      - name: Publish All
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
      - name: Publish base
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd website-base
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..
      - name: Publish docusaurus
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd website-docusaurus
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..
      - name: Publish hexo
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd website-hexo
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..
      - name: Publish react
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd website-react
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..
      - name: Publish vue
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd website-vue
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..
      - name: Publish vuepress
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd website-vuepress
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py